import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const output='test-results';await fs.mkdir(output,{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173/?test');
await page.waitForFunction(()=>window.bicycleDiagnostics?.ready);
assert.equal((await page.evaluate(()=>window.bicycleDiagnostics.rider())).bones,18);
await page.locator('#welcome-difficulty').selectOption('extreme');
assert.equal(await page.locator('.brand,.menu-note,.scene-caption,.eyebrow').count(),0);
await page.waitForTimeout(500);
await page.screenshot({path:output+'/01-menu.png'});
await page.getByRole('button',{name:'操作方式'}).click();
assert.equal(await page.locator('#controls-panel').isVisible(),true);
await page.screenshot({path:output+'/02-controls.png'});
await page.getByRole('button',{name:'关闭操作方式'}).click();
await page.getByRole('button',{name:'开始骑行'}).hover();await page.waitForTimeout(250);
assert.notEqual(await page.locator('#start').evaluate(e=>getComputedStyle(e).transform),'none');
await page.getByRole('button',{name:'开始骑行'}).click();
assert.equal(await page.getByRole('dialog').isVisible(),true);
const helpPosition=await page.evaluate(()=>window.bicycleDiagnostics.snapshot().position);
await page.waitForTimeout(200);
assert.deepEqual(await page.evaluate(()=>window.bicycleDiagnostics.snapshot().position),helpPosition);
await page.screenshot({path:output+'/11-key-help.png'});
await page.getByRole('button',{name:'知道了，开始骑行'}).click();
await page.waitForTimeout(250);
assert.equal(await page.locator('#menu-shell').isVisible(),false);
assert.equal(await page.locator('#debug').isVisible(),false);
await page.screenshot({path:output+'/03-first-person.png'});
await page.keyboard.down('Space');await page.waitForTimeout(150);
await page.screenshot({path:output+'/04-pedals.png'});await page.keyboard.up('Space');
await page.keyboard.down('q');await page.keyboard.down('e');await page.waitForTimeout(450);
await page.keyboard.up('q');await page.keyboard.up('e');
const pushed=await page.evaluate(()=>window.bicycleDiagnostics.snapshot());
console.log('real keyboard push',pushed);
assert.ok(pushed.speed>.15,'Q ground push / E pedal must generate movement');
await page.keyboard.press('v');await page.waitForTimeout(100);
await page.screenshot({path:output+'/05-third-person.png'});
await page.keyboard.press('F3');
assert.equal(await page.locator('#debug').isVisible(),true);
await page.keyboard.press('h');assert.equal(await page.getByRole('dialog').isVisible(),true);
await page.keyboard.press('h');assert.equal(await page.getByRole('dialog').isVisible(),false);
await page.keyboard.press('Escape');await page.waitForTimeout(100);
assert.equal(await page.locator('#menu-shell').isVisible(),true);
const beforePause=await page.evaluate(()=>window.bicycleDiagnostics.snapshot());
await page.waitForTimeout(150);
const afterPause=await page.evaluate(()=>window.bicycleDiagnostics.snapshot());
assert.deepEqual(beforePause.position,afterPause.position,'pause must freeze physics');
await page.getByRole('button',{name:'设置',exact:false}).first().click();
await page.locator('#camera').selectOption('first');
await page.locator('#volume').fill('0.25');
await page.screenshot({path:output+'/06-settings.png'});
await page.getByRole('button',{name:'回到起点',exact:true}).click();
await page.keyboard.press('F3');
await page.keyboard.press('z');
await page.waitForTimeout(3500);
const fallen=await page.evaluate(()=>window.bicycleDiagnostics.snapshot());
assert.equal(fallen.fallen,true,'unsupported bike must fall in browser');
await page.screenshot({path:output+'/07-fall.png'});
await page.keyboard.press('r');await page.waitForTimeout(250);
assert.equal((await page.evaluate(()=>window.bicycleDiagnostics.snapshot())).fallen,false);
await page.keyboard.press('Escape');
await page.setViewportSize({width:900,height:650});await page.screenshot({path:output+'/08-compact.png'});
await page.setViewportSize({width:390,height:844});await page.screenshot({path:output+'/09-mobile-menu.png'});
await page.reload();await page.waitForFunction(()=>window.bicycleDiagnostics?.ready);
assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('manual-bicycle.settings.v1')).volume),.25);
await page.setViewportSize({width:1440,height:900});
await page.getByRole('button',{name:'开始骑行'}).click();
await page.keyboard.down('d');await page.waitForTimeout(140);await page.keyboard.up('d');
assert.ok((await page.evaluate(()=>window.bicycleDiagnostics.snapshot())).bodyX<-.03,'D must move toward the first-person right (-X)');
await page.keyboard.down('a');await page.waitForTimeout(220);await page.keyboard.up('a');
assert.ok((await page.evaluate(()=>window.bicycleDiagnostics.snapshot())).bodyX>.03,'A must move toward the first-person left (+X)');
await page.mouse.move(1150,500);await page.waitForTimeout(150);
assert.ok((await page.evaluate(()=>window.bicycleDiagnostics.snapshot())).steer<-.03,'mouse right must steer toward the first-person right');
await page.keyboard.press('r');await page.waitForTimeout(1000);
await page.keyboard.down('Space');await page.waitForTimeout(100);
await page.screenshot({path:output+'/10-final-pedals.png'});await page.keyboard.up('Space');
await page.keyboard.press('Escape');await page.getByRole('button',{name:'设置',exact:false}).first().click();
await page.locator('summary').click();
await page.getByRole('button',{name:'修改左脚踩踏 / 蹬地键位'}).click();
await page.keyboard.press('t');
assert.equal(await page.getByRole('button',{name:'修改左脚踩踏 / 蹬地键位'}).textContent(),'T');
await page.getByRole('button',{name:'关闭设置'}).click();
await page.getByRole('button',{name:'继续骑行'}).click();
await page.keyboard.down('t');await page.waitForTimeout(350);await page.keyboard.up('t');
assert.ok((await page.evaluate(()=>window.bicycleDiagnostics.snapshot())).speed>.2,'rebound pedal key must still push off');
assert.deepEqual(errors,[]);
console.log('Browser checks passed; screenshots:',output);
await browser.close();
