import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
await fs.mkdir('test-results',{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
  const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:5173/?test');await page.waitForFunction(()=>window.bicycleDiagnostics?.ready);
  assert.equal(await page.locator('#welcome-difficulty').inputValue(),'training');
  assert.equal(await page.locator('#welcome-difficulty-caption').textContent(),'体验有辅助轮的畅快自行车生活');
  await page.waitForFunction(()=>window.bicycleDiagnostics.trainingVisible());
  await page.screenshot({path:'test-results/comfort-menu.png'});
  await page.locator('#start').click();await page.locator('#dismiss-help').click();
  await page.waitForFunction(()=>window.bicycleDiagnostics.music().time>.15);
  assert.equal((await page.evaluate(()=>window.bicycleDiagnostics.music())).loop,true);
  assert.equal(await page.locator('#speedometer').isVisible(),true);
  // Pedal-only start through actual input; release must retain momentum.
  await page.keyboard.down('e');await page.waitForTimeout(700);await page.keyboard.up('e');
  const before=await page.evaluate(()=>window.bicycleDiagnostics.snapshot());assert.ok(before.speed>.2);
  await page.waitForTimeout(350);const coast=await page.evaluate(()=>window.bicycleDiagnostics.snapshot());
  assert.ok(coast.position.z>before.position.z+.03);assert.ok(coast.speed>.15);
  assert.ok(Number(await page.locator('#speed-value').textContent())>.4);
  await page.screenshot({path:'test-results/comfort-speedometer.png'});
  await page.keyboard.press('h');const musicPause=await page.evaluate(()=>window.bicycleDiagnostics.music());
  assert.equal(musicPause.paused,true);await page.waitForTimeout(180);
  assert.ok(Math.abs((await page.evaluate(()=>window.bicycleDiagnostics.music())).time-musicPause.time)<.05);
  await page.keyboard.press('h');await page.waitForFunction(t=>window.bicycleDiagnostics.music().time>t+.1,musicPause.time);
  await page.keyboard.press('Escape');await page.locator('#open-settings').click();
  await page.locator('#music-volume').fill('0.2');await page.locator('#music-enabled').uncheck();
  await page.locator('#difficulty').selectOption('standard');
  assert.equal((await page.evaluate(()=>window.bicycleDiagnostics.snapshot())).difficulty,'standard');
  await page.waitForFunction(()=>!window.bicycleDiagnostics.trainingVisible());
  await page.screenshot({path:'test-results/comfort-settings.png'});
  await page.locator('summary').click();
  const binding=name=>page.getByRole('button',{name:`修改${name}键位`,exact:true});
  await binding('前刹车').click();await page.keyboard.press('f');
  await binding('后刹车').click();await page.mouse.click(28,25);
  assert.equal(await binding('后刹车').textContent(),'鼠标左键');
  await binding('左脚踩踏 / 蹬地').click();await page.keyboard.press('e');
  assert.equal(await binding('左脚踩踏 / 蹬地').textContent(),'E');
  assert.equal(await binding('右脚踩踏 / 蹬地').textContent(),'Q');
  await binding('车把向右（可选）').click();await page.keyboard.press('ArrowRight');
  await binding('暂停').click();await page.keyboard.press('p');
  await binding('物理调试').click();await page.keyboard.press('Delete');
  assert.equal(await binding('物理调试').textContent(),'未绑定');
  await binding('前刹车').click();await page.keyboard.press('Escape');
  assert.equal(await binding('前刹车').textContent(),'F');
  await page.getByRole('button',{name:'关闭设置'}).click();await page.locator('#start').click();
  assert.equal((await page.evaluate(()=>window.bicycleDiagnostics.music())).paused,true);
  await page.keyboard.down('f');assert.equal((await page.evaluate(()=>window.bicycleDiagnostics.input())).frontBrake,true);await page.keyboard.up('f');
  await page.mouse.down();assert.equal((await page.evaluate(()=>window.bicycleDiagnostics.input())).rearBrake,true);await page.mouse.up();
  await page.keyboard.down('ArrowRight');await page.waitForTimeout(180);await page.keyboard.up('ArrowRight');
  assert.ok((await page.evaluate(()=>window.bicycleDiagnostics.input())).steer<-.08);
  await page.keyboard.press('p');assert.equal(await page.locator('#menu-shell').isVisible(),true);
  await page.reload();await page.waitForFunction(()=>window.bicycleDiagnostics?.ready);
  assert.equal(await page.locator('#welcome-difficulty').inputValue(),'standard');
  const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('manual-bicycle.settings.v1')));
  assert.equal(saved.bindings.frontBrake,'KeyF');assert.equal(saved.bindings.rearBrake,'Mouse0');assert.equal(saved.musicVolume,.2);
  await page.locator('#open-settings').click();await page.locator('#music-enabled').check();
  await page.locator('summary').click();await page.locator('#reset-bindings').click();
  assert.equal(await binding('前刹车').textContent(),'鼠标左键');assert.equal(await binding('暂停').textContent(),'Esc');
  await page.locator('#difficulty').selectOption('extreme');
  assert.equal(await page.locator('#difficulty-caption').textContent(),'体验暴力铃兰骑自行车的痛苦。切换后原地重新摆正。');
  await page.getByRole('button',{name:'关闭设置'}).click();await page.locator('#start').click();
  await page.waitForFunction(()=>!window.bicycleDiagnostics.music().paused);
  await page.keyboard.press('h');assert.ok((await page.locator('#help-start').textContent()).includes('保留原始物理'));
  assert.deepEqual(errors,[]);
  console.log('Difficulty, real BGM playback/pause, speed and coasting, keyboard/mouse rebinding, swapping, clearing and persistence passed.');
}finally{await browser.close();}
